### ISSUE TITLE
issueベースの開発レビュー依頼

### ISSUE THREAD

**Issue by kana-54b** [kana-54b/MemoSprout#26]

**Comment by kana-54b** [comment]
### ■Webアプリの概要
その日の出来事を一言で記録し、なぜそう感じたかを深掘りすることで思考を整理するアプリです。
「なぜ？」「どこが？」と具体的に問いかけることで、思考の明確化を促します。

簡単に始められるように、一言入力というシンプルな形式を採用しました。

「短時間でできる深い自己理解」を提供し、毎日少しずつ成長を感じられる点が最大の魅力です。特に、シンプルな操作性と自己分析を手助けする誘導質問機能が特徴です。
　

### ■1週間辺りの開発に向けられる時間
- 1週間あたり：28時間
1週間あたりのストーリポイント消化目安：14
　

### ■ProjectsのURL
https://github.com/users/kana-54b/projects/1
　

### ■MVPリリースまで
- [ ] Dockerファイルの作成
- [ ] rails new
- [ ] Fly.ioにデプロイ
- [ ] トップページの作成
- [ ] ヘッダー・フッターの設置
- [ ] ユーザー登録ページ
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] 新規作成ページ
- [ ] 確認（プレビュー）ページ
- [ ] 記録詳細ページ
- [ ] 記録一覧ページ
- [ ] アプリのシェア機能（X)
- [ ] フィードバックページ
- [ ] パスワードリセット申請ページ
- [ ] パスワード変更ページ

　
### ■MVPリリース後（変更の可能性有り）
- [ ] ファビコン
- [ ] ページタイトルの動的表示
- [ ] ページネーション機能
- [ ] 記録編集機能
- [ ] 記録削除機能
- [ ] 記録のお気に入り登録機能
- [ ] 記録のお気に入り削除機能
- [ ] 感情の選択機能（「喜」のみから「怒」「哀」「楽」の追加）
- [ ] google認証機能
- [ ] 累計記録回数・連続記録日数の表示機能
- [ ] LINEリマインダー機能
- [ ] 記録別のシェア機能
- [ ] 記録回数に応じた可視化システム（記録回数に基づいて木や花が育つような視覚的アプローチ）
- [ ] OpenAIによる振り返りレポート機能
- [ ] レポートのお気に入り登録機能
- [ ] レポートのお気に入り削除機能
- [ ] 記録の自動分析機能（レポート機能と被る？）
- [ ] 記録回数に応じて変化を可視化するシステム
- [ ] 使い方ページの充実化（感情別による入力例の表示）
　

### ■MVPレビュー依頼予定日
予定日：2024年 10月 29日

**Comment by kenchasonakai** [comment]
LGTMです！
