### ISSUE TITLE
10/31 MVPレビュー依頼

### ISSUE THREAD

**Issue by kana-54b** [kana-54b/MemoSprout#27]

**Comment by kana-54b** [comment]
## 各種情報
サービスの概要とMVPで検証する事柄：
一つの出来事に対して掘り下げ、新たな気付きを発見したり、感情の整理をするアプリです。

簡単に始められるように、一言入力というシンプルな形式を採用しました。

「短時間でできる深い自己理解」を提供し、毎日少しずつ成長を感じられる点が最大の魅力です。特に、シンプルな操作性と自己分析を手助けする誘導質問機能が特徴です。


サービス名：
Memo Sprout（めも すぷらうと）
サービスURL：https://memo-sprout.fly.dev/


## READMEレビュー時にMVPリリース時点で実装予定だった機能
（スケジュール面談後のissueを参照しています）
- [ ] トップページ
- [ ] ヘッダー・フッターの設置
- [ ] ユーザー登録ページ
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] 新規作成ページ
- [ ] 確認（comfirm）ページ
- [ ] 記録詳細ページ
- [ ] 記録一覧ページ

## READMEレビュー時から変更した機能
【作らなくなった機能】
- [ ] フォームの追加出現
「なぜ？をもっと深める」ボタンをクリックでフォームを追加出現機能を取りやめ

【追加した機能】
MVP後に実装予定だった以下2点を追加しています。
- [ ] ゲストログイン機能
- [ ] 記録編集機能
- [ ] 記録削除機能

## サービスイメージがわかるようなスクリーンショット等
Topページ
<a href="https://gyazo.com/e85e423c1c51abda26f3690385570d9e"><img src="https://i.gyazo.com/e85e423c1c51abda26f3690385570d9e.png" alt="Image from Gyazo" width="1438"/></a>
- 登録なしで使えるゲストログインボタンを用意しました。
- Topページにログインフォームを設置しています。

ログイン後のTopページ
[![Image from Gyazo](https://i.gyazo.com/9633490042a7134b0bc3f6500b0e8434.png)](https://gyazo.com/9633490042a7134b0bc3f6500b0e8434)
- ログインフォームを非表示にしています。（ゲストログインも同様）

記録一覧ページ
[![Image from Gyazo](https://i.gyazo.com/94c35649f97afec38532a539a3c03553.jpg)](https://gyazo.com/94c35649f97afec38532a539a3c03553)
- 最終更新したメモを上部に表示、その下に一覧で表示しています。
- 一覧のタイトル部分にはglass buttonを適用し、クリックしやすくしました。

新規作成ページ
[![Image from Gyazo](https://i.gyazo.com/f92bbf950a421a6f3d8b9cf0dcf8e229.png)](https://gyazo.com/f92bbf950a421a6f3d8b9cf0dcf8e229)
[![Image from Gyazo](https://i.gyazo.com/056b3a5dce7ef9f4d41fdb1a5f251de3.png)](https://gyazo.com/056b3a5dce7ef9f4d41fdb1a5f251de3)
- エンターキーで誤送信を防ぐために全てのフォームに`text_area`を使用しています。
- 「書き方例」ボタンクリックでモーダルが出現します。
[![Image from Gyazo](https://i.gyazo.com/84fce9f8adbba87b7a98f4ffaf550961.png)](https://gyazo.com/84fce9f8adbba87b7a98f4ffaf550961)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by kana-54b** [comment]
ありがとうございます。
本リリースに向けて引き続き頑張ります！
