### ISSUE TITLE
お気に入り機能をturbo_streamで反映

### ISSUE THREAD

**Issue by kana-54b** [kana-54b/MemoSprout#71]

**Comment by kana-54b** [comment]
## 聞きたいこと・アドバイスが欲しいこと
#### お気に入り機能の☆と★の切り替えを、turbo_streamを使用して非同期通信したいです。
どの部分を見直したらいいのかと、おすすめの検証方法をアドバイスいただけないでしょうか🙇‍♀️

[![Image from Gyazo](https://i.gyazo.com/360de1d39812dacc5e0eaa23a078b65b.png)](https://gyazo.com/360de1d39812dacc5e0eaa23a078b65b)
`commit`は成功していますが `No template`エラーが発生します。
  
 
## 実装の際に参考にした資料等
参考にしているのはRails基礎の14,15です。
  
  
## 現状のコードの状態がわかるURL(プルリクエスト・リポジトリ等)
[現状のコード(最終のプルリクエスト)](https://github.com/kana-54b/MemoSprout/pull/70)です。
  
  
## どこが関係していると考えているのか
メモ一覧
app/views/memos/index.html.erb
```
<% @memos.each do |memo| %>
  ...
  <div id="favorite-star-<%= memo.id %>">
    <%= render "shared/favorite_star", memo: memo %> <!-- お気に入りの⭐️表示 -->
  </div>
  ...
<% end %>
```
  
  
@memoは memos#index
```
  def index
    @memos = current_user.memos.includes(:user).order(created_at: :desc).page(params[:page]).per(5)
  end
```
  
  
`render "shared/favorite_star"`で
app/views/shared/_favorite_star.html.erbが呼ばれる
```
<div class='ms-auto'>
  <% if current_user.favorite_memo?(memo) %> # ここの(memo)に@memoが入っている
    <%= render "shared/star_favorite", memo: memo %> <!-- ★ -->
  <% else %>
    <%= render "shared/star_unfavorite", memo: memo %> <!-- ☆ -->
  <% end %>
</div>
```
  
  
`render "shared/star_favorite"`で
app/views/shared/_star_favorite.html.erbが呼ばれる。
`memo.id`を使って `memo_favorite_path`に `memo`をわたす。
```
<!-- お気に入り済み　黒い星 クリックでお気に入り解除-->
<%= link_to memo_favorite_path(memo), # (memo)に @memo
    id: "favorite-star-#{memo.id}",
    data: { turbo_method: :delete } do %> 
  <i class="fa-solid fa-star"></i> <!-- ★ -->
<% end %>
```
  
※ `turbo_method: :delete`で `memo_favorites#destroy`が動く
**ここはプルリクエストのURLから変更しています**
  ```
# 現在
  def destroy
    @memo_favorite = MemoFavorite.find(params[:id])
    @memo = @memo_favorite.memo
    @memo_favorite.destroy!

    Rails.logger.debug "Request フォーマット📂: #{request.format}" 
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to memo_favorites_path }
      end
  end
```
**destroyメソッドで処理が終了します。**
  
  
  

期待する動きは `@memo_favorite.destroy!`で `views/memo_favorites/destroy.turbo_stream.html.erb`が表示されることです。
しかしログに `No template found for MemoFavoritesController#destroy, rendering head :no_content`というエラーが出ており、`destroy.turbo_stream.html.erb`を見つけられていないようです。
  
  
  
## 検証した結果から分かったこと・考えたこと
1. パスではなくファイルそのものを表示しようとしました
```
    Rails.logger.debug "Request フォーマット📂: #{request.format}" 
      respond_to do |format|
        format.turbo_stream
        format.html { render :destroy } # ファイルを表示しようとした
      end
```

2. ディレクトリ構造が違う可能性を考え、memo_favoritesから memosに移動しました。
3. memoのidが取得できていない・もしくは重複している可能性を考えましたが、こちらの検証方法が分からず実施できていません。
4. createメソッドとdestroyメソッドは正しく動いているため、viewの問題で解決できるとわかりました。[![Image from Gyazo](https://i.gyazo.com/33663a56dae615ccf3b874278620a58c.png)](https://gyazo.com/33663a56dae615ccf3b874278620a58c)
[![Image from Gyazo](https://i.gyazo.com/ce648fbebbcc057c8af1b03ac7d6bdf2.png)](https://gyazo.com/ce648fbebbcc057c8af1b03ac7d6bdf2)
連動しています。
[![Image from Gyazo](https://i.gyazo.com/3d8bb5e82e402fa30973b421abf84524.png)](https://gyazo.com/3d8bb5e82e402fa30973b421abf84524)
[![Image from Gyazo](https://i.gyazo.com/da3f0c5f8b2572c3435c5a251f9b5ae3.png)](https://gyazo.com/da3f0c5f8b2572c3435c5a251f9b5ae3)
5. ログに`Request フォーマット📂: text/vnd.turbo-stream.html`と出ているのでリクエスト自体は正しくturbo_streamとして処理されていることがわかっています。


---

色々と試したため、もう一度create, destroyアクションのコードの見直しをすすめます。
よろしくお願いいたします🙇‍♀️

**Comment by kenchasonakai** [comment]
貼っていただいたプルリクからは`app/views/memo_favorites/destroy.turbo_stream.html.erb`がないように見えますね
ファイルがきちんと存在するか確認してみてください
https://github.com/kana-54b/MemoSprout/tree/feature/issue66-memo-favorites/app/views/memo_favorites

**Comment by kana-54b** [comment]
失礼いたしました。該当ファイルをpushしていませんでした💦

- app/views/memo_favorites/create.turbo_stream.html.erb
- app/views/memo_favorites/destroy.turbo_stream.html.erb
以上2点をpushしましたので、お手数ですが再度ご確認いただけますでしょうか🙇‍♀️
https://github.com/kana-54b/MemoSprout/tree/feature/issue71-turbo_stream/app/views/memo_favorites

**Comment by kana-54b** [comment]
No templateエラーの原因はファイル名の間違いでした。
`html`が入っていたことにより読み取れなかったようです。
- ~~app/views/memo_favorites/create.turbo_stream.html.erb~~ 
→app/views/memo_favorites/create.turbo_stream.erb
  
- ~~app/views/memo_favorites/destroy.turbo_stream.html.erb~~
→app/views/memo_favorites/destroy.turbo_stream.erb

現状読み込めるようになったので、他の問題点がないか確認をします。
進捗がありましたらコメントと、質問フォームからご報告いたします！

**Comment by kana-54b** [comment]
問題なく動くことを確認できましたので、こちらの内容は解決といたします。
ありがとうございました🙇‍♀️✨
